<a href="https://colab.research.google.com/github/porcelainruler/intro-to-dl/blob/master/Practice/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf;
%tensorflow_version 2.x

import numpy as np;

TensorFlow is already loaded. Please restart the runtime to change versions.


In [4]:
N = 1000;
D = 3;

x = np.random.random((N, D));
w = np.random.random((D, 1));

# 2nd part introduces NOISE so as to make it as real data
y = x@w + np.random.randn(N, 1) * 0.20             # Linear Regression Equation

tf.reset_default_graph();

print(x);
print(w);
# print(y);

[[0.21831256 0.33613848 0.2066049 ]
 [0.87703119 0.15238611 0.08458685]
 [0.28767065 0.31763691 0.311852  ]
 ...
 [0.40865052 0.44940294 0.46837451]
 [0.93844284 0.22702981 0.55641361]
 [0.06041591 0.16160346 0.66281878]]
[[0.15124757]
 [0.90585536]
 [0.054317  ]]


In [6]:
# Placeholder Define
features = tf.placeholder(tf.float32, shape = (None, D));
target = tf.placeholder(tf.float32, shape = (None, 1));

# Making Prediction
weight = tf.get_variable("w", shape = (D, 1), dtype = tf.float32);
prediction = features @ weight;

# Loss Function
loss = tf.reduce_mean((prediction - target) ** 2);

# Optimzer
optimiser = tf.train.GradientDescentOptimizer(0.1);
step = optimiser.minimize(loss);

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [11]:
# Solving Linear Regrssion 
s = tf.InteractiveSession()

# If Training takes a lot of time use checkpointing ans save results at regular intervals
saver = tf.train.Saver(tf.trainable_variables())
s.run(tf.global_variables_initializer());


# Running 300 interations
for i in range(300) :
  _, curr_loss, curr_weight = s.run([step, loss, weight], feed_dict = {features:x, target:y});

  if(i % 50 == 0):
    # saver.save(s, "logs/2/model.ckpt", global_step = i)                             **Saving at each 50 iterations 
    print(loss);

# Checkpoint Restoraion by                          || We ahave to define the same graph before restoring checkpoint
'''    saver.restore("logs/2/model.ckpt");    '''


/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


Tensor("Mean:0", shape=(), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)


'    saver.restore("logs/2/model.ckpt");    '